[build]
  command = "ng build --configuration production && echo '{\"apiUrl\": \"'$API_URL'\"}' > dist/portfolio-frontend/browser/config.json"
  publish = "dist/portfolio-frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
